ARG base
FROM "${base}"

# Check if all desired locales are there.
RUN locale -a | grep -i 'c\.utf-\?8' \
    && \
    locale -a | grep -i 'en_us\.utf-\?8'

RUN apt-get update -qq \
    && \
    apt-get install --yes --no-install-recommends \
      ca-certificates \
      wget \
    && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && \
    sh ./Miniconda3-latest-Linux-x86_64.sh -bp /opt/conda \
    && \
    /opt/conda/bin/conda info --all
