ARG base
FROM "${base}"

# Check if env-activate.sh gets sourced for login shell and in env-execute.
RUN [ "$( sh -lc 'printf world' )" = 'world' ] \
    && \
    [ "$( /usr/local/env-execute sh -c 'printf world' )" = 'world' ] \
    && \
    printf '%s\n' \
      'printf "hello "' \
      > /usr/local/env-activate.sh \
    && \
    [ "$( sh -lc 'printf world' )" = 'hello world' ] \
    && \
    [ "$( /usr/local/env-execute sh -c 'printf world' )" = 'hello world' ] \
    && \
    printf '' \
      > /usr/local/env-activate.sh

# Check if all desired locales are there.
RUN locale -a | grep -i 'c\.utf-\?8' \
    && \
    locale -a | grep -i 'en_us\.utf-\?8'

RUN apt-get update -qq \
    && \
    apt-get install --yes --no-install-recommends \
      ca-certificates \
      wget \
    && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && \
    sh ./Miniconda3-latest-Linux-x86_64.sh -bp /opt/conda \
    && \
    /opt/conda/bin/conda info --all
