ARG base
FROM "${base}"

# Check if env-activate.sh gets sourced for login shell and in env-execute.
RUN [ "$( sh -lc 'printf world' )" = 'world' ] \
    && \
    [ "$( /usr/local/env-execute sh -c 'printf world' )" = 'world' ] \
    && \
    printf '%s\n' \
      'printf "hello "' \
      > /usr/local/env-activate.sh \
    && \
    [ "$( sh -lc 'printf world' )" = 'hello world' ] \
    && \
    [ "$( /usr/local/env-execute sh -c 'printf world' )" = 'hello world' ] \
    && \
    printf '' \
      > /usr/local/env-activate.sh

COPY --from=debian:9-slim /lib/x86_64-linux-gnu/libz.so* /lib/x86_64-linux-gnu/
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && \
    sh ./Miniconda3-latest-Linux-x86_64.sh -bp /opt/conda \
    && \
    /opt/conda/bin/conda info --all
