ARG base
FROM "${base}"

COPY --from=debian:9-slim /lib/x86_64-linux-gnu/libz.so* /lib/x86_64-linux-gnu/

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && \
    sh ./Miniconda3-latest-Linux-x86_64.sh -bp /opt/conda \
    && \
    /opt/conda/bin/conda info --all
