name: 'Build & Push: bioconda-recipes-issue-responder'
on:
  push:
    branches:
    - main
    paths:
    - images/bioconda-recipes-issue-responder/*
    - .github/workflows/bioconda-recipes-issue-responder.yaml
  pull_request:
    paths:
    - images/bioconda-recipes-issue-responder/*
    - .github/workflows/bioconda-recipes-issue-responder.yaml

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: bioconda-recipes-issue-responder
      IMAGE_VERSION: '1.1.1'

    steps:
    - uses: actions/checkout@v2

    - name: Build
      id: buildah-build
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: >-
          latest
          ${{ env.IMAGE_VERSION }}
        context: ./images/${{ env.IMAGE_NAME }}
        dockerfiles: |
          ./images/${{ env.IMAGE_NAME }}/Dockerfile

    - name: Test
      run: |
        image='${{ steps.buildah-build.outputs.image }}'
        ids="$(
          for tag in ${{ steps.buildah-build.outputs.tags }} ; do
            buildah images --quiet --no-trunc "${image}:${tag}"
          done
          )"
        ids="$( printf %s "${ids}" | sort -u )"
        for id in ${ids} ; do
          podman history "${id}"
          buildah bud \
            --build-arg=base="${id}" \
            --file=Dockerfile.test \
            "images/${image}"
        done
        buildah rmi --prune || true

    - name: Check Tags
      run: |
        # FIX upstream: Quay.io does not support immutable images currently.
        #               => Try to use the REST API to check for duplicate tags.
        respone="$(
          curl -sL \
            'https://quay.io/api/v1/repository/bioconda/${{ steps.buildah-build.outputs.image }}/image'
          )"

        existing_tags="$(
          printf %s "${respone}" \
            | jq -r '.images[].tags[]'
          )" \
          || {
            printf %s\\n \
              'Could not get list of image tags.' \
              'Does the repository exist on Quay.io?' \
              'Quay.io REST API response was:' \
              "${respone}"
            exit 1
          }
        for tag in ${{ steps.buildah-build.outputs.tags }} ; do
          if [ \! "${tag}" = latest ] ; then
            if printf %s "${existing_tags}" | grep -qxF "${tag}" ; then
              printf 'Tag %s already exists!\n' "${tag}"
              exit 1
            fi
          fi
        done

    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Push
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.buildah-build.outputs.image }}
        tags: ${{ steps.buildah-build.outputs.tags }}
        registry: ${{ secrets.QUAY_BIOCONDA_REPO }}
        username: ${{ secrets.QUAY_BIOCONDA_USERNAME }}
        password: ${{ secrets.QUAY_BIOCONDA_TOKEN }}

    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Test Pushed
      run: |
        image='${{ steps.buildah-build.outputs.image }}'
        ids="$(
          for tag in ${{ steps.buildah-build.outputs.tags }} ; do
            buildah images --quiet --no-trunc "${image}:${tag}"
          done
          )"
        ids="$( printf %s "${ids}" | sort -u )"
        for id in ${ids} ; do
          podman history "${id}"
          buildah bud \
            --build-arg=base="${id}" \
            --file=Dockerfile.test \
            "images/${image}"
        done
        buildah rmi --prune || true
